module Ct(erlps__fail__1) where
{-
This file has been autogenerated
DO NOT EDIT - Your changes WILL be overwritten
Use this code at your own risk - the authors are just a mischievous raccoon and a haskell devote
Erlscripten v0.1.0
-}

import Prelude
import Data.Array as DA
import Data.List as DL
import Data.Maybe as DM
import Data.Map as Map
import Data.Tuple as Tup
import Data.BigInt as DBI
import Erlang.Builtins as BIF
import Erlang.Binary as BIN
import Erlang.Helpers as H
import Erlang.Exception as EXC
import Erlang.Type (ErlangFun, ErlangTerm(..), weakCmp, weakEq,
                    weakNEq, weakLt, weakLeq, weakGeq, weakGt)
import Effect (Effect)
import Effect.Unsafe (unsafePerformEffect)
import Effect.Exception (throw)
import Partial.Unsafe (unsafePartial)


erlps__fail__1 :: ErlangFun
erlps__fail__1 [arg_0] =
  let    arg_2 = (H.make_string "TEST FAILED: ~p\n")
  in let
    arg_1 =
      (BIF.do_remote_fun_call "Io.Lib" "erlps__format__2"
         [arg_2, (ErlangCons arg_0 ErlangEmptyList)])
  in let
    _ =
      (BIF.do_remote_fun_call "Erlang.Io" "erlps__put_chars__1"
         [arg_1])
  in (BIF.erlang__throw__1 [(ErlangAtom "failed")])
erlps__fail__1 [arg_7] = (EXC.function_clause unit)
erlps__fail__1 args =
  (EXC.badarity
     (ErlangFun 1 (\ _ -> (ErlangAtom "purs_tco_sucks"))) args)